### ISSUE TITLE
rflags missing NT and RES bits

### ISSUE THREAD

**Issue by TretornESP** [kot-org/Kot#14]
**Describe the bug**

The _rflags_t_  defined in [cpu.h](https://github.com/kot-org/Kot/blob/0f99fd2062d6051f8593b96478a3a9d0d02fd2cd/Sources/Kernel/Src/arch/x86-64/cpu/cpu.h) is missing the following fields:

_Nested task flag — Controls the chaining of interrupted and called tasks. Set when the
current task is linked to the previously executed task; cleared when the current task is not
linked to another task._

__Reserved bit 15__

Which might cause alginment issues

[Reference](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-1-manual.pdf)

**Comment by YiraSan** [comment]
You're right NT and RES are missing, I'll fix that right now!
![image](https://github.com/kot-org/Kot/assets/45128167/074a0d45-d575-41c4-91b8-eae9e0a4865f)
